{
  "description": "This is a continuation of a series called Tales from the Ops Side. Back in November 2016, a seemingly innocuous piece of code that has been running for years starts throwing a very strange and nonsensical exception. This strange exception seemed to be thrown completely at random, could not be reproduced in any other environment, and would also self-heal! This talk tells the story of a baffling bug hunt spread over many weeks, involved all members of the company, including the CEO and CTO, and lead us deep into the guts of CPython and countless dead-ends.\n\nPresentation page -- https://2017.pycon.ca/schedule/32/",
  "duration": 1652,
  "recorded": "2017-11-18",
  "language": "en",
  "speakers": [
    "Hany Fahim"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/G6iqIIpW9Cw/hqdefault.jpg",
  "title": "Unpacking an anomaly",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=G6iqIIpW9Cw"
    }
  ]
}
